version: "3.9"

services:

  main:
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html